
GET http://localhost:3000/players
###

POST http://localhost:3000/players/
Content-Type:application/json

{
    "playerName":"Vishal",
    "jerseyNumber":17,
    "role":"Bowler"
}
###
GET http://localhost:3000/players/1/
###

PUT http://localhost:3000/players/
Content-Type:application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rou
}

###
DELETE http://localhost:3000/players/2/

